### PR TITLE
wip: pulled out p5 svelte to test some new features

### PR DESCRIPTION
**Pull request by edw1nzhao**
This is an example of pulling out the p5 specific code. looks like the best way might be to pull the entire sketch out like this. 

Thoughts + was spending a lot of time trying to optimize it, it is DARN slow.

### CODE REVIEW

**Comment by edw1nzhao** [comment]
@BenRydal some pretty significant changes in this one so far, looking forward to hearing your thoughts on how this is going so far.

**Comment by BenRydal** [comment]
Ok thinking through this today! A few thoughts. First, the program is super slow because the convertFileToUsers function is not filtering out any data--I think we need to carefully refactor that function soon to optimize it, make it clearer so we can see potential issues, and also handle errors. For example, I think we are creating users within the forEach loop on the csvData when that should come before the loop. Then I think we need to reduce the data and that should speed up both processing and displaying.

**Comment by BenRydal** [comment]
For your other refactoring--am I right that what you've done is created igsSketch file (which calls a new p5.ts file to) and pulled into that tons of stuff from the previous page.svelte file and then moved a bunch of stuff to core.ts right? I noticed there were 2 visualize data functions (one in IGS sketch and one in the new p5.ts file---the one here is not used yet but I assume will replace the other one). This all makes sense to me. Did not quite clearly now what the new p5.ts file is for. And then we need to carefully think through what the core.ts file is and refine those methods. This all feels good to me. So next steps if this felt good I think are 1) refactor/finalize the convertFileToUsers so we add speed to the program for testing, 2) refine the core.ts file so we can remove other dead code in there beyond commenting it out. Am I missing anything big from changes you made!?

**Comment by edw1nzhao** [comment]
> Ok thinking through this today! A few thoughts. First, the program is super slow because the convertFileToUsers function is not filtering out any data--I think we need to carefully refactor that function soon to optimize it, make it clearer so we can see potential issues, and also handle errors. For example, I think we are creating users within the forEach loop on the csvData when that should come before the loop. Then I think we need to reduce the data and that should speed up both processing and displaying.

Yeah I think that refactor is going to be important. That makes sense, let me try doing that this week.

**Comment by edw1nzhao** [comment]
> For your other refactoring--am I right that what you've done is created igsSketch file (which calls a new p5.ts file to) and pulled into that tons of stuff from the previous page.svelte file and then moved a bunch of stuff to core.ts right? I noticed there were 2 visualize data functions (one in IGS sketch and one in the new p5.ts file---the one here is not used yet but I assume will replace the other one). This all makes sense to me. Did not quite clearly now what the new p5.ts file is for. And then we need to carefully think through what the core.ts file is and refine those methods. This all feels good to me. So next steps if this felt good I think are 1) refactor/finalize the convertFileToUsers so we add speed to the program for testing, 2) refine the core.ts file so we can remove other dead code in there beyond commenting it out. Am I missing anything big from changes you made!?

You're right about that. I'll get rid of the other visualize data as soon as possible. The next steps make sense and those are exactly the changes that I intended.

**Pull request merged**
